# Generated by Django 4.1.3 on 2022-11-29 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Débito", "Debit"),
                            ("Crédito", "Credit"),
                            ("Boleto", "Ticket"),
                            ("Financiamento", "Financing"),
                            ("Recebimento Empréstimo", "Loan"),
                            ("Vendas", "Sale"),
                            ("Recebimento TED", "Ted"),
                            ("Recebimento DOC", "Doc"),
                            ("Aluguel", "Rent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                ("value", models.PositiveIntegerField()),
                ("cpf", models.CharField(max_length=50)),
                ("card", models.CharField(max_length=50)),
                ("establishment", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
            ],
        ),
    ]
